### ISSUE TITLE
Metals: dap-mode hangs on Windows 10

### ISSUE THREAD

**Issue by raggaraluz** [emacs-lsp/dap-mode#319]
Hello,

I'm having the same error as in #295, but using metals (scala) back-end.

I've tried updating dap-mode and lsp-mode to the latest version, but the issue is not fixed yet, at least for metals. The versions are dap-mode-20200731.1910 and lsp-mode-20200731.1945 respectively. lsp-metals is also updated to lsp-metals-20200727.1925

On the other hand, when if I set `(setq inhibit-eol-conversion t)` globally, dap debugger works fine.

Thanks!

**Comment by yyoncho** [comment]
Hi @Eli-Zaretskii

How can I set inhibit-eol-conversion per network-stream:


Here it is the relevant part from dap-mode:

``` emacs-lisp
(open-network-stream session-name nil
                     host port
                     :type 'plain
                     :coding 'no-conversion)
....
(defun dap--parser-read (p output)
  (let* ((output (encode-coding-string output 'utf-8 'nocopy)))

    (let ((body-sep-pos (string-match-p "\r\n\r\n" chunk)))
      ....
      )))
```

**Comment by Eli-Zaretskii** [comment]
You cannot set `inhibit-eol-conversion` per stream, you need to bind it to a non-nil value when you actually perform the conversion.  If you bind `coding-system-for-read` or `coding-system-for-write`, or if you specify the coding-system explicitly in the calls to `encode-coding-string` etc, use the `*-unix` variety of the coding system (as in `utf-8-unix`) to inhibit EOL conversion.

I don't think I understand the example you show to give more specific advice.

**Comment by yyoncho** [comment]
Thank you @Eli-Zaretskii . I think that this is what I was looking for.

@raggaraluz can you test if https://github.com/emacs-lsp/dap-mode/commit/bd37f1f3ca24ad560447e4ef4d2ed488b197d89f fixes your issue?

**Comment by raggaraluz** [comment]
Thanks @yyoncho, but bd37f1f is not working for me 😞.

However, I've tried to change the coding to **utf-8-dos** and it works fine. I assume the messages are effectively in dos format, and changing them to *-unix makes it to fail.

Any hint on how to make it work in both windows and linux?

**Comment by Eli-Zaretskii** [comment]
If the fix in `bd37f1f` is not working, but globally setting `inhibit-eol-conversion` non-nil does, then the problem is not only in encoding stuff, but also in decoding it.

**Comment by yyoncho** [comment]
I pushed 58a372f which tries to fix the issue on a larger scale. Can you try it?

**Comment by raggaraluz** [comment]
I've tried and it does not work yet.

I've been making some clumsy debugging of the elisp code, and got some findings regarding the funcion `dap--parser-read`.
```
(defun dap--parser-read (p output)
  "Parser OUTPUT using parser P."
  (let* ((inhibit-eol-conversion t)
         (messages '())
         (output (encode-coding-string output 'utf-8 'nocopy))
         (chunk (concat (dap--parser-leftovers p) output)))
    (while (not (string-empty-p chunk))
      (if (not (dap--parser-reading-body p))
          ;; Read headers
          (let* ((body-sep-pos (string-match-p "\r\n\r\n" chunk)))
```

* When entering the function, the variable `output` has already the line breaks in the form of `\n` instead of `\r\n`. Therefore, the inhibit-eol-conversion has no effect here. The eol conversion is being made somewhere before the call to `dap--parser-read`.

* If I change the `utf-8` to `utf-8-dos` when calling encode-coding-string, the `\r\n` are back to the output variable. With this change, everything is working fine, as all the matches with `\r\n\r\n` works. It looks for me as a suitable solution, in case it works for linux as well (I cannot test it).


Finally, I've been cheking the documentation of `open-network-stream` [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Network.html), and I don't see the option `:coding no-conversion` in it. May I have some missing package which enables it? Or is it just a undocumented function parameter?

**Comment by yyoncho** [comment]
If the conversion has happened before that method then it has happened in the
process handling code in emacs core because this function is what we pass as a
filter via `set-process-filter`. I tested setting `utf-8-dos` as encoding in
`encode-coding-string` and it works fine on Linux. Unfortunately, I do not have
enough knowledge to tell if this won't break other cases.


@Eli-Zaretskii here it is what we do:

``` emacs-lisp

(open-network-stream session-name nil
   host port :type 'plain
   :coding 'no-conversion)
```

Then we set the filter via `set-process-filter` and the string received in
`dap--parser-read` contains `\n\n\n\n` instead of `\r\n\r\n` on windows.

**Comment by Eli-Zaretskii** [comment]
In general, if you use `no-conversion` when opening a stream, there should be no conversions whatsoever, neither character encoding conversions nor EOL conversions.  So your assertion that "the conversion has happened in the process handling code" doesn't seem to be correct.

However, you didn't tell what does the process filter function do; maybe it performs some conversions?

In general, I feel that I don't have a clear idea how things are related here.  E.g., `dap--parser-read` uses `encode-coding-string`, which sounds strange, since parsing should generally *decode*, not encode.  Also, where does its `output` argument come from?  Is it something received from the network, or something to be sent to the network?  I guess I'm missing the bird-eye view of what happens there.

**Comment by Eli-Zaretskii** [comment]
And another thing that puzzles me: if the code expects to see `\r\n`, then how does it work on GNU/Linux? what produces the `\r` part there?

**Comment by yyoncho** [comment]
> In general, I feel that I don't have a clear idea how things are related here.
> E.g., `dap--parser-read` uses `encode-coding-string`, which sounds strange,
> since parsing should generally *decode*, not encode.


Maybe this is not the right way or the most efficient way to perform the task at
hand(I am not considering myself an expert in that area, also I am not the
original author of that particular piece of code): ATM the encoding is needed in
order to count correctly the multibyte symbols in the stream

Here it is a snippet from the tests:
``` emacs-lisp
  (let ((p (make-dap--parser)))
		(should (equal (dap--parser-read p "Content-Length: 18\r") nil))
		(should (equal (dap--parser-read p "\n\r\n{\"somedata\":\"\xe2\x80") nil))
		(should (equal (dap--parser-read p "\x99\"}Content-Length: 14\r\n\r\n{")
									 '("{\"somedata\":\"’\"}")))
		(should (equal (dap--parser-read p "\"somedata\":2}")
									 '("{\"somedata\":2}"))))
```


> Also, where does its `output` argument come from? Is it something received
> from the network, or something to be sent to the network?

It is something received from the stream, and we do not touch it up to that point.

> And another thing that puzzles me: if the code expects to see `\r\n`, then how
> does it work on GNU/Linux? what produces the `\r` part there?

The stream itself or this is not a valid answer?


> In general, if you use `no-conversion` when opening a stream, there should be no
> conversions whatsoever, neither character encoding conversions nor EOL

Maybe this is the answer - it seems like(or at least on emacs 27.0.91) the
`:no-conversion` is not passed to `make-network-process`.

**Comment by kiennq** [comment]
> E.g., `dap--parser-read` uses `encode-coding-string`, which sounds strange, since parsing should generally _decode_, not encode.

The original code is using `string-as-unibyte`, and Emacs advice us to use `encode-coding-string` instead.
Also see https://github.com/emacs-lsp/dap-mode/pull/279#discussion_r425472144

**Comment by yyoncho** [comment]
> The original code is using `string-as-unibyte`, and Emacs advice us to use
> `encode-coding-string` instead. Also see
> https://github.com/emacs-lsp/dap-mode/pull/279#discussion_r425472144

Yes - my point here is that we are using this strategy for handling multibyte
strings, the particular conversion function doesn't matter that much. Probably
there might be more efficient ways to perform the parsing(e. g. decode directly
in the process or different function for counting the length of the string).

**Comment by Eli-Zaretskii** [comment]
> the encoding is needed in order to count correctly the multibyte symbols in the stream

Please describe in more detail what do you mean by "multibyte symbols".  What do you want to count, and why?

> Here it is a snippet from the tests:

Sorry, but this doesn't tell me enough.  I see that some results are nil, and some others are lists of strings.  Not sure what this is supposed to explain or clarify.

> [`output`] is something received from the stream

Then it makes no sense to encode it: it is already encoded.  Encoding is the process of taking the *internal* Emacs representation of a string and converting it to one of the external representations, which are strings encoded in some known codeset, such as UTF-8.  Decoding is the opposite process: take a string from the outside world (a disk file or a network connection) and convert it into the internal representation Emacs uses.

> it seems like(or at least on emacs 27.0.91) the `:no-conversion` is not passed to make-network-process.

Indeed, it isn't.  This is new in Emacs 28.  If you are using Emacs 27, you need to manually set the coding-systems of the process after you create it, see `set-process-coding-system`.

**Comment by Eli-Zaretskii** [comment]
> The original code is using string-as-unibyte, and Emacs advice us to use encode-coding-string instead.

The input from the network process is already unibyte.

Once again, if you tell what you are trying to do with this "unibyte" string, maybe I could advise how to implement it.

**Comment by Eli-Zaretskii** [comment]
> different function for counting the length of the string

Do you need length in bytes or in characters?

**Comment by yyoncho** [comment]
> > the encoding is needed in order to count correctly the multibyte symbols in
> > the stream
>
> Please describe in more detail what do you mean by "multibyte symbols". What do
> you want to count, and why?

A bit shorter example, here it is sample message for the dap protocol(which is not JSONRPC, FTR)

``` emacs-lisp
(equal (dap--parser-read (make-dap--parser)
                         "Content-Length: 18\r\n\r\n{\"somedata\":\"\xe2\x80\x99\"}")
       '("{\"somedata\":\"’\"}"))
```

`Content-Length: 18` means - the number of chars that the json message has. What
we do right now, we look for "\r\n\r\n", parse the headers and then take
`Content-Length` symbols from that stream. In order that to work, we convert the
string to `utf-8` otherwise `length`/`substring` wont match the number `18` due
to `\xe2\x80\x99`.

In general, it will be great if we can optimize that because it will reduce the
pressure on garbage collector.

(sorry for not using the proper terminology)

>
> Indeed, it isn't. This is new in Emacs 28. If you are using Emacs 27, you need
> to manually set the coding-systems of the process after you create it, see
> `set-process-coding-system`.
>

I will try that.

**Comment by yyoncho** [comment]
@raggaraluz - can you test f950e0d?

**Comment by Eli-Zaretskii** [comment]
> Content-Length: 18 means - the number of chars that the json message has

Characters or bytes?  Given what you say later, I'm guessing bytes.  If my guess is correct, then reading the message into a unibyte string and taking its `length` will do what you want.  Then take as many characters (actually bytes) from the unibyte string, and *decode* it to give you a multibyte string to use.

**Comment by yyoncho** [comment]
> Characters or bytes?

Here it is the dap spec:

```
The content part contains the actual content of the message. The content part of a message uses JSON to describe requests, responses, and events.

The content part is encoded using utf-8.
```

So I assume that bytes = chars?


> Given what you say later, I'm guessing bytes. If my guess is correct, then
> reading the message into a unibyte

This means passing coding-system `unibyte` to the process?

> string and taking its `length` will do what you want. Then take as many
> characters (actually bytes) from the unibyte string, and *decode* it to give
> you a multibyte string to use.


Will this be more efficient compared to what we do now?

**Comment by Eli-Zaretskii** [comment]
> So I assume that bytes = chars?

I'm not sure.  I still think it's bytes.  That's how things are in other network protocols.

> This means passing coding-system unibyte to the process?

No, using `no-conversion` already does that.  You just need to verify that `output` is a unibyte string, using `multibyte-string-p`.

> Will this be more efficient compared to what we do now?

If you tell me in what source files to look for which functions that are involved in this processing, I can try answering that question.  But in any case, what I wrote was meant to make the code simpler and more easy to understand, so that it looks less like some black magic that you don't understand.

**Comment by Eli-Zaretskii** [comment]
After taking a quick look at the code, I think you should try removing this line:

         (output (encode-coding-string output 'utf-8 'nocopy))

The rest of the code clearly assumes the stuff you get from the network stream is a unibyte bytestream which needs to be decoded as UTF-8 to yield readable text.

Does the repo history reveal why this line (or its predecessor that used `string-as-unibyte`) was introduced into the code?
Any specific problem?

**Comment by yyoncho** [comment]
> Does the repo history reveal why this line (or its predecessor that used `string-as-unibyte`) was introduced into the code?
> Any specific problem?

Here it is the test that was introduces with that change:

```
(let ((p (make-dap--parser)))
	  (should (equal (dap--parser-read p "Content-Length: 238\r\n\r\n{\"event\":\"output\",\"body\":{\"category\":\"stdout\",\"output\":\"2019-01-13 00:16:36  [ main ] - [ INFO com.inspur.common.utils.PropertiesBuilder.getConfig(32)]  从jar内加载:kafka-producer.properties\\n\",\"type\":\"output\"},\"seq\":9,\"type\":\"event\"}") '("{\"event\":\"output\",\"body\":{\"category\":\"stdout\",\"output\":\"2019-01-13 00:16:36  [ main ] - [ INFO com.inspur.common.utils.PropertiesBuilder.getConfig(32)]  从jar内加载:kafka-producer.properties\\n\",\"type\":\"output\"},\"seq\":9,\"type\":\"event\"}"))))
```

This fails right now if I the call to `encode-coding-string`. It fails on line `(substring chunk 0 (min left-to-receive chunk-length))` with args out of range.

**Comment by yyoncho** [comment]
@Eli-Zaretskii that you for taking a look at this. I think that issue mentioned in my previous comment is something caused by dap-mode parsing logic and `encode-coding-string` is indeed redundant but somehow introduces side effect which fixes the issue. I tested on lsp-mode side, which has much improved and optimized parsing and it is able to handle the input that fails on dap-mode side even with encode-coding-string.I will do additional testing tomorrow, but it seems that in the end that we will be able to remove the encode call. Thanks again.

**Comment by Eli-Zaretskii** [comment]
> Here it is the test that was introduces with that change

Can you show the full error message for the failed test?  I want to see the length argument that was incorrect.

**Comment by raggaraluz** [comment]
> @raggaraluz - can you test [f950e0d](https://github.com/emacs-lsp/dap-mode/commit/f950e0d240db5e1e2a978daaa01d11b3d7deed8a)?

Hi @yyoncho, I've just tested it and works fine for me. Thanks!

**Comment by Eli-Zaretskii** [comment]
I've looked into the test shown above, and I'm now pretty sure the Content-Length is measured in bytes, not in characters.

**Comment by yyoncho** [comment]
> Can you show the full error message for the failed test? I want to see the
> length argument that was incorrect.

Here it is:

eval: Args out of range: "{\"event\":\"output\",\"body\":{\"category\":\"stdout\",\"output\":\"2019-01-13 00:16:36  [ main ] - [ INFO com.inspur.common.utils.PropertiesBuilder.getConfig(32)]  从jar内加载:kafka-producer.properties\\n\",\"type\":\"output\"},\"seq\":9,\"type\":\"event\"}", 0, 237

**Comment by Eli-Zaretskii** [comment]
Thanks.  This is what I'd expect: you have a multibyte string created from the output, and you are trying to index it using a byte offset.  The length of that string in characters is 230, and its length in bytes is 238.

So the problem is that at some point you take a unibyte input string and convert it to a multibyte string, possibly when you `concat` it with another string.
