### ISSUE TITLE
Lacking feature to send strings from stdin interactively?

### ISSUE THREAD

**Issue by aki-s** [emacs-lsp/dap-mode#58]
Could you debug code which requests input from `stdin` such as below?
```
int main() {
     scanf("%d", &t); // <- Input is expected from stdin.
...
    // Conditional operation which depends input from stdin.
   // ...
}
```

---

I've investigated on Linux.
I could track down, that when `M-x dap-debug` is done, the following sequence has arisen.
1. [https://github.com/llvm-mirror/lldb/tree/master/tools/lldb-vscode](lldb-vscode) is started.
1. lldb-vscode started `lldb-server gdbserver --fd=6 --native-regs --setsid`.

It seems lldb-vscode and lldb-server is communicating with unnamed socket, but lldb-vscode has no option to send `stdin` to `lldb-server`. I get stucked here...

**Comment by yyoncho** [comment]
The protocol itself does not support sending stdin (unless I am mistaken) pretty much because vscode console does not support stdin I guess. The other adapters support running the application in external terminal or attaching to an existing app but from what I can see this one does not. So the options here are:

1. File a bug on lldb-vscode to support either attach or starting the process in external terminal(or point us to documentation on how to do that).
2. Integrate with vscode-lldb which do support running in external console (https://github.com/vadimcn/vscode-lldb )
3. Try debugging with Native debug which also supports lldb and it is integrated with dap-mode but the attach templates+the instructions are not part of dap ATM. 

see also: https://github.com/Microsoft/vscode-go/issues/219

**Comment by aki-s** [comment]
Thank you for very quick response and much of support.

> vscode console does not support stdin

lldb project itself may try to support external `stdin`, but it seems to be stopped in the end
ref. http://lists.llvm.org/pipermail/lldb-dev/2014-March/003735.html

My current minimum requirement was actually static input, so setting
```
$ lldb
> settings set target.input-path /path/to/file/STATIC-INPUT.txt
```
was suffice.

I have read lldb-vscode.cpp, and I found only `target.source-map` is set directly before `launch` unfortunately ↓
https://github.com/llvm-mirror/lldb/blob/master/tools/lldb-vscode/lldb-vscode.cpp#L432
https://github.com/llvm-mirror/lldb/blob/master/tools/lldb-vscode/lldb-vscode.cpp#L2605

I might create `void request_settings(const llvm::json::Object &request)` method, to set `target.input-path`... but I have no so much of time.
I'll give up, so I'll close this issue once.

Thank you very much again. :+1:
