### ISSUE TITLE
No delegateCommandHandler for vscode.java.resolveClasspath

### ISSUE THREAD

**Issue by didibus** [emacs-lsp/dap-mode#65]
When running lsp-java with dap-mode, and trying to run `dap-java-run-test-class` or `dap-java-run-test-method` I get the error:

```
No delegateCommandHandler for vscode.java.resolveClasspath
```

Anything I'm supposed to setup to get this to work?

My tests are JUnit 4.

**Comment by yyoncho** [comment]
The issue is that the methods needed for resolving the classpath are not present in the jdt ls server. They are provided by the java debug adapter bundle. You may inspect the server methods by doing lsp-describe-session and then expanding the capabilities node. First, make sure that you have the java debug server bundle installed by doing  `lsp-java-update-server` and restarting the jdt ls server.

**Comment by didibus** [comment]
Running `lsp-java-update-server` worked for me.

Thanks! Love all your work on lsp!

**Comment by ivanhjc** [comment]
> The issue is that the methods needed for resolving the classpath are not present in the jdt ls server. They are provided by the java debug adapter bundle. You may inspect the server methods by doing lsp-describe-session and then expanding the capabilities node. First, make sure that you have the java debug server bundle installed by doing `lsp-java-update-server` and restarting the jdt ls server.

Running `M-x lsp-java-update-server` always fails on me because the downloading of `jdt-language-server-latest.tar.gz` is so slow that eventually it reports timeout. Is there a way to do it manually? Please see my question on [Emacs stackexchange](https://emacs.stackexchange.com/questions/54262/how-to-update-lsp-java-manually) for more details.

**Comment by yyoncho** [comment]
@ivanhjc posted a solution in stackexchange. This is one way to do it - download the pom.xml that does the job, remove the sections that download and unzip the server and execute leave the rest of the sections. Let me know if it works.

**Comment by ivanhjc** [comment]
@yyoncho Yes it works! Thanks a lot :D
