### ISSUE TITLE
[DAP-CHROME] Template for debugging in chrome

### ISSUE THREAD

**Issue by Majenful** [emacs-lsp/dap-mode#87]
Hello everyone!

First I want to thank all the contributors and maintainers of **LSP** projects, it's a fantastic toolbelt for emacs!

I'm currently on an ionic/cordova project. I like to debug my app with chrome. 

To do it I use **Visual Studio Code** + **Debugger For Chrome**
And the following config:
```
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        },
```

How can I convert this template to **dap-mode** template? Especially the _webRoot_ (since dap-mode seems to require a file and not a directory

Thanks :)

**Comment by yyoncho** [comment]
> Especially the webRoot (since dap-mode seems to require a file and not a directory

The issue is in the registered template. Chrome debug adapter supports multiple(?) templates and I have ported only one of them since I am not JS programmer and it is difficult for me to test all scenarios/templates. You have few options:

1. Do dap-debug-edit-template which and then convert your config to emacs one (e. g. url will become `:url`, etc). You will have to populate workspaceFolder with the path to your workspace folder since we do not support templates ATM. Then execute the code and you will have that template via dap-debug. 

2. Do a PR against dap-chrome.el to provide one more key webRoot and populate it with `(lsp-workspace-root)` (refer to `dap-chrome--populate-start-file-args`).

3. Provide me with JS test project and steps to debug it in vscode and I will reproduce it in Emacs.

**Comment by Majenful** [comment]
Thanks for the quick response!

For 1.
So I can translate all parameters and add _workspaceFolder_ instead of _webRoot_ and put the path of my project directory?

For 3.
I cannot give you the current project (it is company project) but I may give you a Hello world ionic project?

**Comment by yyoncho** [comment]
> For 1.
> So I can translate all parameters and add _workspaceFolder_ instead of _webRoot_ and put the path of my project directory?

No, the keys are the same. You should change `"${workspaceFolder}"` with the path to the actual workspace folder root (e. g. the folder that contains package.json).
 
> For 3.
> I cannot give you the current project (it is company project) but I may give you a Hello world ionic project?

That would work too.

**Comment by Majenful** [comment]
I didn't try your solution yet

Please find a sample project:
https://github.com/Majenful/myApp

You need to install ionic/cordova
```
npm install
ng serve

```
In Visual Studio Code, you need **Debugger for Chrome**
and this config
```
"configurations": [

        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        }
    ]
```
